### ISSUE TITLE
Cards that don't work

### ISSUE THREAD

**Issue by dxt298** [AngelOfSol/chaos_js_translate#1]
Cards that cause the script to freeze entirely:
http://chaos-tcg.com/cardlist/?cardno=DC-170
http://chaos-tcg.com/cardlist/?cardno=IM-054
http://chaos-tcg.com/cardlist/?cardno=IM-048
http://chaos-tcg.com/cardlist/?cardno=IM-056

**Comment by AngelOfSol** [comment]
Closed by fixing infinite loop.
